export const exceptions = {
  NOT_FOUND_EXCEPTION: 404,
  UN_AUTHORIZED_NOT_FOUND_EXCEPTION: 401,
  BAD_REQUEST_EXCEPTION: 400,
  FORBIDDEN_EXCEPTION: 403,
  FATAL_ERROR_EXCEPTION: 500,
  UNPROCESSABLE_ENTITY_EXCEPTION: 422,
  OK: 200,
  CREATED: 201,
  CONFLICT: 409,
};
